version: "3.4"
services:

  app:
    build: ./users
    container_name: "auth-service"
    volumes:
      - .:/go/src/auth-service
    tty: true
    ports:
      - "9000:9000"
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo:3.2.21-jessie
    container_name: auth-db
    ports:
      - "27017:27017"
    volumes:
      - ./db:/db:rw
